module.exports = {
  apps: [
    {
      name: 'oudnomad-api',
      cwd: '/var/www/oudnomad/apps/api',
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        DATABASE_URL: 'postgresql://postgres:postgres@127.0.0.1:5432/oudnomad?schema=public',
        REDIS_URL: 'redis://127.0.0.1:6379',
        KAFKA_BROKER: '127.0.0.1:9092',
        OPENSEARCH_NODE: 'http://127.0.0.1:9200',
        STORAGE_DRIVER: 'local',
        UPLOAD_DIR: '/var/www/oudnomad/apps/api/uploads',
        PUBLIC_STORAGE_URL: 'https://oudnomaddubai.com/uploads',
        FRONTEND_URL: 'https://oudnomaddubai.com',
        PAYMENT_PROVIDER: 'stripe',
        DEFAULT_CURRENCY: 'AED',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'oudnomad-web',
      cwd: '/var/www/oudnomad/apps/web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://oudnomaddubai.com/api',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'oudnomad-worker',
      cwd: '/var/www/oudnomad/apps/notification-worker',
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
        KAFKA_BROKERS: '127.0.0.1:9092',
        KAFKA_BROKER: '127.0.0.1:9092',
        EMAIL_PROVIDER: 'smtp',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
  ],
};
